- name: Sample
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World
    - name: Install httd Package
      ansible.builtin.package:
        name: httpd
        state: absent
    - name: Check Uptime
      ansible.builtin.shell: /usr/bin/uptime



